[package]
name = "main_game_loop"
version = "0.1.1"
edition = "2021"
description = "A game loop with event handling"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
log = "0.4.16"
glam = "0.20.3"

# sdl2 = "0.35.2"
gilrs = "0.8.2"
